### ISSUE TITLE
Implement debouncing for search bar

### ISSUE THREAD

**Issue by EinarBalan** [uclaacm/dev-pathways#16]
As described [here](https://hack.uclaacm.com/posts/fall2019/js-chats-3/#application-power-of-hooks-with-debouncing).

This is probably overkill for the amount of resources we have atm, but would be good for future proofing. Outside of scope of MVP fs.

**Comment by matthewcn56** [comment]
Have you tried using the [useDebounce custom hook](https://usehooks.com/useDebounce/) from useHooks? (The logic for handling debouncing can be contained to just a single custom hook).
